sudo: false
language: node_js
node_js:
- '8'
- '10'
- '12'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/surge.bash)"
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: n24TBPQUOqW8EMqLPekbaYREIpjnmch2E2U52nrVbIxxet7FttRGAa0OQVHzgd7hUM0PnLglfxmaafdvawh0+lR5goSHW5aKZM7gr3MIxK/AR+Uz7zO0RK66kasdU5WpRQRVkmalnUZ9D+2nC/+6K1Jsof/OjC7nefZAuO/C55u3LAUmOYmeUNce8g7mcI24qLqTZhMoMa41C5z/63lNSjO3mXHoYKkz81u9lUWRbS4Wv8Al+eKc+Zj5RWQ50rf2SOYBGXpEUOWU2Woqz04HpJosrvDJ+2yjrrPIPRNY63KjJDTrryUYyHFORcZVopWoQ4Wvl3v3uXbnJo3bWUq/u0eTbpGb7n6LvnUi7kAcd6Y1GfnODIue0EIqMtx79VKp4l1wMnKEeDUuH4wA39/TXK6/KewLs6WO28g7xgE6CGYX33jFhzAdJF68ZFyXwUpVPxrXG6Sd8b67Aqdbz3NL7RH4UdldN+v/s5VnjsdXi40OmN1OuW7B4zGhgFMMEidHwPVnSpz16NrHa0kGo+BZqX/Ua6QgjQ2ZVV6juBRBqJfLsyq03md60IuA9Y2q9Pe6r0zjypYxHxnTBenYjVHtSQNzeqI35STniP5Bfchey+LEVpWLQtDqqgRnStCNKLDt0YY/JdYWhhkAtCL/5UQyjw0hn8c0DQCS3m9s2oI2K+U=
