sudo: false
language: node_js
node_js:
- '8'
- '10'
- '12'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-install.bash)"
before_script:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-verify.bash)"
after_success:
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/surge.bash)"
- eval "$(curl -fsSL https://raw.githubusercontent.com/bevry/awesome-travis/c91c9d5eef34ecb0e92029667fd5052640225fa3/scripts/node-publish.bash)"
notifications:
  email:
    recipients:
      secure: LbdUm7DCp5uMU5lyLPeAi57rlkyMmGWsc0KtJ9vL6gT5nDrLxxathjk9cNXQRXrPy0VU+vXWxg+eSC4kquH2ymQEC0BxfozW3iHAB8oa9QDaiD4xdjHEh5womQWQbUuWuWyE3R1vHpPV17K28KuLTQCr66sbAV0cN92/kL4FY6n1sYYyPuT7sQe9P880QSOx6hgz344NxUkn/oFDpfl4I/aEZDw76l/Kt64nU64FtvXtYv78eu6f+aePbkbGSvJx/jl6jXVZup6LgPMMLWZVkAfkRNPTgMmd/qF4XXjZ7Bix2AHuqo+s6CvmDH4/YqTqT3T5ovdpl4CnGcuILdMOTxVA/1adeoB5J5mZHBQqzw79WMfjv/BD/j5blEYySWIsRjNd/sDLLxkx50bYXdNW5jyrX8ZaNlORnHrSM7DpfuqoTaCD5hl9SKBgOQxU3ZnoAoqxDXGrm/YqsWJsXFlO7xXg9clp/4+jls5F+2zQ8RZSY2O/PN/CjK8lhkFtRvMkK9Flj+sc+6zKdYb5/K4iphy+7NGXVjCLqJyuKDZzYAIrtT6ZdHY6sjVKD7EV0n7UaphqzCdtwHB8Kn1ZtsbwGrps0YXuTxHb+kD/WDT12/jGJiN8L94zBU9xt6mIrGStRxr8Att0BV61CRNNGqTabCQB1NVzptKfDyZFm4N+qxk=
